# Generated by Django 6.0.5 on 2026-05-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=150, verbose_name='Nombre del solicitante')),
                ('contacto', models.CharField(max_length=150, verbose_name='Email/Contacto')),
                ('tipo_falla', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de falla')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('direccion_area', models.CharField(max_length=150, verbose_name='Dirección/Área')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='abierto', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas de seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
