# Generated by Django 6.0.5 on 2026-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('otro', 'Otro')], default=None, max_length=20, null=True, verbose_name='Tipo de falla'),
        ),
    ]
