# Generated by Django 6.0.5 on 2026-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=150)),
                ('direccion_area', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('software', 'Software'), ('red', 'Red'), ('otro', 'Solicitud de servicio')], default='otro', max_length=20, null=True, verbose_name='Tipo de falla'),
        ),
    ]
