# Generated by Django 6.0.5 on 2026-05-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_notificacionusuario_alter_ticket_tipo_falla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento fallido de inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('CAMBIAR_PASSWORD', 'Cambio de contraseña')], max_length=50, verbose_name='Acción')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo afectado')),
                ('id_objeto', models.IntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles')),
                ('direccion_ip', models.CharField(max_length=45, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
