# Generated by Django 6.0.5 on 2026-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_migrar_tipificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='direccion_area',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Dirección/Departamento'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento fallido de inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ACCESO', 'Acceso al panel'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('CAMBIAR_PASSWORD', 'Cambio de contraseña')], max_length=50, verbose_name='Acción'),
        ),
    ]
